export const blogs = [
    {
        id: 1,
        postName: 'UX review presentations',
        postImage: '/images/blog/ux.png',
        author: 'Olivia Rhye',
        date: '20 Jan 2022',
        image: '/images/about/olivia.png',
        category: 'Design',
        description: "How do you create compelling presentations that wow your...",
    },
    {
        id: 2,
        postName: 'Migrating to Linear 101',
        postImage: '/images/blog/product.png',
        author: 'Phoenix Baker',
        date: '19 Jan 2022',
        image: '/images/about/baker.png',
        category: 'Product',
        description: "Linear helps streamline software projects, sprints, tasks, and bu...",
    },
    {
        id: 3,
        postName: 'Building your API Stack',
        postImage: '/images/blog/software.png',
        author: 'Lana Steiner',
        date: '18 Jan 2022',
        image: '/images/about/lana.png',
        category: 'Software Engineering',
        description: "The rise of RESTful APIs has been met by a rise in tools...",
    },
    {
        id: 4,
        postName: 'PM mental models',
        postImage: '/images/blog/mentalProduct.png',
        author: 'Demi Wilkinson',
        date: '17 Jan 2022',
        image: '/images/about/demi.png',
        category: 'Product',
        description: "Mental models are simple expressions of complex...",
    },
    {
        id: 5,
        postName: 'What is Wireframing?',
        postImage: '/images/blog/wireframe.png',
        author: 'Candice Wu',
        date: '16 Jan 2022',
        image: '/images/about/wu.png',
        category: 'Design',
        description: "Introduction to Wireframing and its Principles. Learn from the...",
    },
    {
        id: 6,
        postName: 'How collaboration makes us better designers',
        postImage: '/images/blog/collaboration.png',
        author: 'Natali Craig',
        date: '15 Jan 2022',
        image: '/images/about/natali.png',
        category: 'Design',
        description: "Collaboration can make our...",
    },
    {
        id: 7,
        postName: 'Our top 10 Javascript frameworks to use in 2022',
        postImage: '/images/blog/top.png',
        author: 'Drew Cano',
        date: '14 Jan 2022',
        image: '/images/about/cano.png',
        category: 'Product',
        description: "JavaScript frameworks make...",
    },
    {
        id: 8,
        postName: 'Podcast: Creating a better CX Community',
        postImage: '/images/blog/customer.png',
        author: 'Orlando Diggs',
        date: '10 Jan 2022',
        image: '/images/about/diggs.png',
        category: 'Customer Success',
        description: "Starting a community doesn’t...",
    },
]